package templates
spring:
  profiles:
    active: dev

  thymeleaf:
    view-names: /*
    cache: false
    prefix: /WEB-INF/html

    server:
      port: 8888

    spring:
     datasource
      username=localhost
      password=123
      url=jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      driver-class-name=com.mysql.jdbc.Driver


